services:
  - type: web
    name: sample
    env: node
    branch: main
    repo: https://github.com/Loki-Xer/jarvis-md.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        value:
